# Dev and debug of statevector.py

In [1]:
import statevector
from statevector import *
print(statevector.__file__)

c:\Users\Jacopo\Codes\quantum\quantum-portfolio\foundations\src\states\statevector.py


In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
# Basis state
s = basis_state(index=7,num_qubits=3)
print(s)

[0. 0. 0. 0. 0. 0. 0. 1.]


In [ ]:
# Normalize
num_qubits = 2
state = basis_state(0,num_qubits) + np.complex64(0,1)*basis_state(1,num_qubits) - basis_state(3,num_qubits)
print(state)
print(normalize(state))

[ 1.+0.j  0.+1.j  0.+0.j -1.+0.j]
[ 0.57735027+0.j          0.        +0.57735027j  0.        +0.j
 -0.57735027+0.j        ]
[ 0.57735027+0.j          0.        +0.57735027j  0.        +0.j
 -0.57735027+0.j        ]


In [70]:
# Is normalized?
print(np.sum(np.abs(normalize(state)**2)))
print(is_normalized(state))
state = np.array([1, 1], dtype=complex)
np.sum(np.abs(normalize(state)**2))
np.abs(normalize(state)**2)
#is_normalized(state)

0.9999999999999998
True


array([0.5, 0.5])

In [52]:
u = basis_state(0,1) + basis_state(1,1)*np.complex64(0,-3)
v = -2*basis_state(1,1)
w = basis_state(0,1)*2 - basis_state(1,1)*5
print(f"u = {u}")
print(f"v = {v}")
print(f"w = {w}")
print(f"Tensor(u,v) = {tensor(u,v)}")
print(f"Tensor(u,v,w) = {normalize(tensor(u,w,v))}")

u = [1.+0.j 0.-3.j]
v = [-0. -2.]
w = [ 2. -5.]
[-0. -2.]
Tensor(u,v) = [-0.+0.j -2.+0.j  0.+0.j  0.+6.j]
[ 2. -5.]
[-0. -2.]
Tensor(u,v,w) = [ 0.        +0.j         -0.11744404+0.j          0.        -0.j
  0.29361011-0.j          0.        +0.j          0.        +0.35233213j
  0.        +0.j         -0.        -0.88083033j]


In [55]:
# Apply operator
operator = 1/np.sqrt(2)*np.array([[1., 1.], [1., -1.]])
state_zero = basis_state(0,1)
state_one = basis_state(1,1)*np.complex64(1,1)
np.matmul(operator,state_one)

array([ 0.70710678+0.70710678j, -0.70710678-0.70710678j])

In [64]:
# Measurement probabilities
state = basis_state(0,1) + basis_state(1,1)*np.complex64(0,1)
state = normalize(state)
print(measurement_probabilities(state))
np.abs(state*state)

[0.5 0.5]


array([0.5, 0.5])

In [67]:
# Inner product
psi = basis_state(0,1)#basis_state(1,1)*np.complex64(0,-1)
phi = basis_state(1,1)#basis_state(0,1) - basis_state(1,1)*np.complex64(1,1)
print(f"psi = {psi}")
print(f"phi = {phi}")
inner_product(psi,phi)

psi = [1. 0.]
phi = [0. 1.]


np.float64(0.0)

In [6]:
num_qubits=1
register_x = basis_state(0,num_qubits)
ancilla = basis_state(1,1)

register = normalize(tensor(ancilla,register_x))
register

[1. 0.]


array([0., 0., 1., 0.])